availability-zone: {{ .Zone }}
cloud-name: "kowabunga"
instance-id: {{ .InstanceID }}
region: {{ .Region }}
kowabunga_metadata_uri: {{ .MetadataEndpoint }}
kowabunga_local_ip: {{ .LocalIP }}
{{ if or (eq .Profile "kawaii") (eq .Profile "konvey") }}
kowabunga_controller_uri: {{ .ControllerEndpoint }}
kowabunga_controller_agent_id: {{ .ControllerAgentID }}
kowabunga_controller_agent_token: {{ .ControllerAgentToken }}
{{ end }}
