version: 2
ethernets:
{{ range . }}
{{ $eth := .}}
  {{ .Device }}:
    match:
      macaddress: {{ .MAC }}
    link-local: []
    accept-ra: false
    dhcp4: false
{{ if .Addresses }}
    addresses:
{{ range .Addresses }}
      - {{ . }}
{{ end }}
{{ if or (.GatewayEnabled) (.Routes) }}
    routes:
{{ if .GatewayEnabled }}
      - to: default
        via: {{ if eq .Profile "kawaii" }}{{ .VLANGateway }}{{ else }}{{ if .Private }}{{ .InternetGateway }}{{ else }}{{ .VLANGateway}}{{ end }}{{ end }}
        metric: {{ if .Private }}200{{ else }}100{{ end }}
{{ end }}
{{ if .Routes }}
{{ range .Routes }}
      - to: {{ . }}
        via: {{ $eth.VLANGateway }}
{{ end }}
{{ end }}
{{ end }}
{{ if or (ne .DNS "") (ne .Domain "") }}
    nameservers:
{{ if ne .DNS "" }}
      addresses:
        - {{ .DNS }}
{{ end }}
{{ if ne .Domain "" }}
      search:
        - {{ .Domain }}
{{ end }}
{{ end }}
{{ end }}

{{ end }}
