#cloud-config
# vim: syntax=yaml
# examples:
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
# Rerun Cloud init from scratch:
# sudo cloud-init clean --logs; sudo cloud-init init --local; sudo cloud-init init; sudo cloud-init modules --mode=config; sudo cloud-init modules --mode=final
ssh_pwauth: false
disable_root: false
hostname: {{ .Hostname }}
fqdn: {{ .Hostname }}.{{ .Domain }}
package_update: true
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
{{ if or (eq .Profile "kawaii") (eq .Profile "konvey") }}
  - keepalived
{{ end }}
users:
  - name: root
    lock_passwd: false
    hashed_passwd: {{ sha512 .RootPassword }}
  - name: {{ .ServiceUser }}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    homedir: /home/{{ .ServiceUser }}
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - {{ .ServiceUserPubKey }}

{{ if ne .Profile "kawaii" }}
{{/* Wait for internet connection, and so Kawaii to pull packets */}}
bootcmd:
- while ! ping -c 1 8.8.8.8; do sleep 5 ;done;
{{ end }}

final_message: "The system is finally up, after $UPTIME seconds"
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "{{ .Hostname }}" > /etc/hostname
{{ if or (eq .Profile "kawaii") (eq .Profile "konvey") }}
  - gpg -k
  - gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/kowabunga.gpg --keyserver keyserver.ubuntu.com --recv-keys 5277E8C721237125
  - chmod 644 /usr/share/keyrings/kowabunga.gpg
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/kowabunga.gpg] http://packages.kowabunga.cloud/ubuntu noble main" > /etc/apt/sources.list.d/kowabunga.repo.list
  - apt-get update
{{ end }}
{{ if eq .Profile "kawaii" }}
  - echo nf_conntrack > /etc/modules-load.d/nf_conntrack.conf
  - systemctl restart systemd-modules-load
  # Strongswan IPSEC
  - apt-get install -y strongswan strongswan-pki strongswan-charon strongswan-libcharon libcharon-extra-plugins libcharon-extauth-plugins libstrongswan-standard-plugins libstrongswan-extra-plugins libtss2-tcti-tabrmd0 charon-systemd
  - systemctl disable strongswan-starter
  - apt-get install -y kowabunga-kawaii-agent
  - systemctl enable kowabunga-kawaii-agent
  - systemctl start kowabunga-kawaii-agent
{{ end }}
{{ if eq .Profile "konvey" }}
  - apt-get install -y traefik
  - apt-get install -y kowabunga-konvey-agent
  - systemctl enable kowabunga-konvey-agent
  - systemctl start kowabunga-konvey-agent
{{ end }}

write_files:
- encoding: b64
  content: {{ .MetadataAlias | b64encode }}
  path: /usr/bin/kw-meta
  permissions: '0755'
