#!/bin/bash

if [ "$1" = install ]; then
    echo "Setting up kowabunga group and kiwi user"

    # creating kowabunga group if he isn't already there
    if ! getent group kowabunga >/dev/null; then
        # Adding system group: kowabunga.
        addgroup --system kowabunga >/dev/null
    fi

    # creating kowabunga kiwi user if he isn't already there
    if ! getent passwd kiwi >/dev/null; then
        # Adding system user: kiwi.
        adduser \
            --system \
            --disabled-login \
            --ingroup kowabunga \
            --no-create-home \
            --home /nonexistent \
            --gecos "Kowabunga Kiwi Agent" \
            --shell /bin/false \
            kiwi >/dev/null
    fi
fi

exit 0
