version: 1
config:
{{ range . }}
{{ if .Addresses }}
  - type: physical
    name: {{ .Device }}
    mac_address: "{{ .MAC }}"
    mtu: 1450
    subnets:
      - type: static
        address: {{ index .Addresses 0 }}
        gateway: {{ .InternetGateway }}
{{ if ne .DNS "" }}
        dns_nameservers:
          - {{ .DNS }}
{{ end }}
{{ if ne .Domain "" }}
        dns_search:
          - {{ .Domain }}
{{ end }}
{{ end }}

{{ end }}
