global:
  logLevel: DEBUG
  publicUrl: "https://site.fqdn"
  adminEmail: admin@acme.com
  jwt:
    signature: SECURE_TOKEN
    lifetimeHours: 24
  http:
    address: 127.0.0.1
    port: 8080
  apiKey: API_KEY
  db:
    uri: "mongodb://127.0.0.1:27017/?directConnection=true"
    name: kowabunga
  cache:
    enabled: true
    type: memory
    sizeMB: 16
    expirationMinutes: 15
  bootstrap:
    user: user
    pubkey: "ssh_pubkey"
  smtp:
    host: "smtp.com"
    port: 587
    from: "John Doe <user@acme.com>"
    username: "user@acme.com"
    password: "PASSWORD"

cloudinit:
  linux:
    userData: /etc/config/templates/linux/user_data.yml
    metaData: /etc/config/templates/linux/meta_data.yml
    networkConfig: /etc/config/templates/linux/network_config.yml
  windows:
    userData: /etc/config/templates/windows/user_data.yml
    metaData: /etc/config/templates/windows/meta_data.yml
    networkConfig: /etc/config/templates/windows/network_config.yml
