// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk

import (
	"context"
	"net/http"
	"errors"
)

// KawaiiAPIService is a service that implements the logic for the KawaiiAPIServicer
// This service should implement the business logic for every endpoint for the KawaiiAPI API.
// Include any external packages or services that will be required by this service.
type KawaiiAPIService struct {
}

// NewKawaiiAPIService creates a default api service
func NewKawaiiAPIService() *KawaiiAPIService {
	return &KawaiiAPIService{}
}

// ListKawaiis - 
func (s *KawaiiAPIService) ListKawaiis(ctx context.Context) (ImplResponse, error) {
	// TODO - update ListKawaiis with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []string{}) or use other options such as http.Ok ...
	// return Response(200, []string{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListKawaiis method not implemented")
}

// ReadKawaii - 
func (s *KawaiiAPIService) ReadKawaii(ctx context.Context, kawaiiId string) (ImplResponse, error) {
	// TODO - update ReadKawaii with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Kawaii{}) or use other options such as http.Ok ...
	// return Response(200, Kawaii{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ReadKawaii method not implemented")
}

// UpdateKawaii - 
func (s *KawaiiAPIService) UpdateKawaii(ctx context.Context, kawaiiId string, kawaii Kawaii) (ImplResponse, error) {
	// TODO - update UpdateKawaii with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Kawaii{}) or use other options such as http.Ok ...
	// return Response(200, Kawaii{}), nil

	// TODO: Uncomment the next line to return response Response(400, ApiErrorBadRequest{}) or use other options such as http.Ok ...
	// return Response(400, ApiErrorBadRequest{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	// TODO: Uncomment the next line to return response Response(422, ApiErrorUnprocessableEntity{}) or use other options such as http.Ok ...
	// return Response(422, ApiErrorUnprocessableEntity{}), nil

	// TODO: Uncomment the next line to return response Response(507, ApiErrorInsufficientResource{}) or use other options such as http.Ok ...
	// return Response(507, ApiErrorInsufficientResource{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateKawaii method not implemented")
}

// DeleteKawaii - 
func (s *KawaiiAPIService) DeleteKawaii(ctx context.Context, kawaiiId string) (ImplResponse, error) {
	// TODO - update DeleteKawaii with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	// TODO: Uncomment the next line to return response Response(409, ApiErrorConflict{}) or use other options such as http.Ok ...
	// return Response(409, ApiErrorConflict{}), nil

	// TODO: Uncomment the next line to return response Response(422, ApiErrorUnprocessableEntity{}) or use other options such as http.Ok ...
	// return Response(422, ApiErrorUnprocessableEntity{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteKawaii method not implemented")
}

// ListKawaiiIpSecs - 
func (s *KawaiiAPIService) ListKawaiiIpSecs(ctx context.Context, kawaiiId string) (ImplResponse, error) {
	// TODO - update ListKawaiiIpSecs with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []string{}) or use other options such as http.Ok ...
	// return Response(200, []string{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListKawaiiIpSecs method not implemented")
}

// CreateKawaiiIpSec - 
func (s *KawaiiAPIService) CreateKawaiiIpSec(ctx context.Context, kawaiiId string, kawaiiIpSec KawaiiIpSec) (ImplResponse, error) {
	// TODO - update CreateKawaiiIpSec with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, KawaiiIpSec{}) or use other options such as http.Ok ...
	// return Response(201, KawaiiIpSec{}), nil

	// TODO: Uncomment the next line to return response Response(400, ApiErrorBadRequest{}) or use other options such as http.Ok ...
	// return Response(400, ApiErrorBadRequest{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	// TODO: Uncomment the next line to return response Response(409, ApiErrorConflict{}) or use other options such as http.Ok ...
	// return Response(409, ApiErrorConflict{}), nil

	// TODO: Uncomment the next line to return response Response(422, ApiErrorUnprocessableEntity{}) or use other options such as http.Ok ...
	// return Response(422, ApiErrorUnprocessableEntity{}), nil

	// TODO: Uncomment the next line to return response Response(507, ApiErrorInsufficientResource{}) or use other options such as http.Ok ...
	// return Response(507, ApiErrorInsufficientResource{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateKawaiiIpSec method not implemented")
}

// ReadKawaiiIpSec - 
func (s *KawaiiAPIService) ReadKawaiiIpSec(ctx context.Context, kawaiiId string, kawaiiIpSecId string) (ImplResponse, error) {
	// TODO - update ReadKawaiiIpSec with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, KawaiiIpSec{}) or use other options such as http.Ok ...
	// return Response(200, KawaiiIpSec{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ReadKawaiiIpSec method not implemented")
}

// UpdateKawaiiIpSec - 
func (s *KawaiiAPIService) UpdateKawaiiIpSec(ctx context.Context, kawaiiId string, kawaiiIpSecId string, kawaiiIpSec KawaiiIpSec) (ImplResponse, error) {
	// TODO - update UpdateKawaiiIpSec with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, KawaiiIpSec{}) or use other options such as http.Ok ...
	// return Response(200, KawaiiIpSec{}), nil

	// TODO: Uncomment the next line to return response Response(400, ApiErrorBadRequest{}) or use other options such as http.Ok ...
	// return Response(400, ApiErrorBadRequest{}), nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	// TODO: Uncomment the next line to return response Response(422, ApiErrorUnprocessableEntity{}) or use other options such as http.Ok ...
	// return Response(422, ApiErrorUnprocessableEntity{}), nil

	// TODO: Uncomment the next line to return response Response(507, ApiErrorInsufficientResource{}) or use other options such as http.Ok ...
	// return Response(507, ApiErrorInsufficientResource{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateKawaiiIpSec method not implemented")
}

// DeleteKawaiiIpSec - 
func (s *KawaiiAPIService) DeleteKawaiiIpSec(ctx context.Context, kawaiiId string, kawaiiIpSecId string) (ImplResponse, error) {
	// TODO - update DeleteKawaiiIpSec with the required logic for this service method.
	// Add api_kawaii_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ApiErrorUnauthorized{}) or use other options such as http.Ok ...
	// return Response(401, ApiErrorUnauthorized{}), nil

	// TODO: Uncomment the next line to return response Response(403, ApiErrorForbidden{}) or use other options such as http.Ok ...
	// return Response(403, ApiErrorForbidden{}), nil

	// TODO: Uncomment the next line to return response Response(404, ApiErrorNotFound{}) or use other options such as http.Ok ...
	// return Response(404, ApiErrorNotFound{}), nil

	// TODO: Uncomment the next line to return response Response(409, ApiErrorConflict{}) or use other options such as http.Ok ...
	// return Response(409, ApiErrorConflict{}), nil

	// TODO: Uncomment the next line to return response Response(422, ApiErrorUnprocessableEntity{}) or use other options such as http.Ok ...
	// return Response(422, ApiErrorUnprocessableEntity{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteKawaiiIpSec method not implemented")
}
