// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// NfsAPIController binds http requests to an api service and writes the service results to the http response
type NfsAPIController struct {
	service NfsAPIServicer
	errorHandler ErrorHandler
}

// NfsAPIOption for how the controller is set up.
type NfsAPIOption func(*NfsAPIController)

// WithNfsAPIErrorHandler inject ErrorHandler into controller
func WithNfsAPIErrorHandler(h ErrorHandler) NfsAPIOption {
	return func(c *NfsAPIController) {
		c.errorHandler = h
	}
}

// NewNfsAPIController creates a default api controller
func NewNfsAPIController(s NfsAPIServicer, opts ...NfsAPIOption) *NfsAPIController {
	controller := &NfsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the NfsAPIController
func (c *NfsAPIController) Routes() Routes {
	return Routes{
		"ListStorageNFSs": Route{
			"ListStorageNFSs",
			strings.ToUpper("Get"),
			"/api/v1/nfs",
			c.ListStorageNFSs,
		},
		"ReadStorageNFS": Route{
			"ReadStorageNFS",
			strings.ToUpper("Get"),
			"/api/v1/nfs/{nfsId}",
			c.ReadStorageNFS,
		},
		"UpdateStorageNFS": Route{
			"UpdateStorageNFS",
			strings.ToUpper("Put"),
			"/api/v1/nfs/{nfsId}",
			c.UpdateStorageNFS,
		},
		"DeleteStorageNFS": Route{
			"DeleteStorageNFS",
			strings.ToUpper("Delete"),
			"/api/v1/nfs/{nfsId}",
			c.DeleteStorageNFS,
		},
		"ListStorageNFSKylos": Route{
			"ListStorageNFSKylos",
			strings.ToUpper("Get"),
			"/api/v1/nfs/{nfsId}/kylo",
			c.ListStorageNFSKylos,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the NfsAPIController
func (c *NfsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ListStorageNFSs",
			strings.ToUpper("Get"),
			"/api/v1/nfs",
			c.ListStorageNFSs,
		},
		Route{
			"ReadStorageNFS",
			strings.ToUpper("Get"),
			"/api/v1/nfs/{nfsId}",
			c.ReadStorageNFS,
		},
		Route{
			"UpdateStorageNFS",
			strings.ToUpper("Put"),
			"/api/v1/nfs/{nfsId}",
			c.UpdateStorageNFS,
		},
		Route{
			"DeleteStorageNFS",
			strings.ToUpper("Delete"),
			"/api/v1/nfs/{nfsId}",
			c.DeleteStorageNFS,
		},
		Route{
			"ListStorageNFSKylos",
			strings.ToUpper("Get"),
			"/api/v1/nfs/{nfsId}/kylo",
			c.ListStorageNFSKylos,
		},
	}
}



// ListStorageNFSs - 
func (c *NfsAPIController) ListStorageNFSs(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ListStorageNFSs(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ReadStorageNFS - 
func (c *NfsAPIController) ReadStorageNFS(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nfsIdParam := params["nfsId"]
	if nfsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"nfsId"}, nil)
		return
	}
	result, err := c.service.ReadStorageNFS(r.Context(), nfsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// UpdateStorageNFS - 
func (c *NfsAPIController) UpdateStorageNFS(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nfsIdParam := params["nfsId"]
	if nfsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"nfsId"}, nil)
		return
	}
	var storageNfsParam StorageNfs
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&storageNfsParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertStorageNfsRequired(storageNfsParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertStorageNfsConstraints(storageNfsParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.UpdateStorageNFS(r.Context(), nfsIdParam, storageNfsParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteStorageNFS - 
func (c *NfsAPIController) DeleteStorageNFS(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nfsIdParam := params["nfsId"]
	if nfsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"nfsId"}, nil)
		return
	}
	result, err := c.service.DeleteStorageNFS(r.Context(), nfsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ListStorageNFSKylos - 
func (c *NfsAPIController) ListStorageNFSKylos(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	nfsIdParam := params["nfsId"]
	if nfsIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"nfsId"}, nil)
		return
	}
	result, err := c.service.ListStorageNFSKylos(r.Context(), nfsIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
