// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Region - A region.
type Region struct {

	// The region ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The region name.
	Name string `json:"name"`

	// The region description.
	Description string `json:"description,omitempty"`

	// Region domain name (e.g. myregion.kowabunga.acme.com).
	Domain string `json:"domain"`
}

// AssertRegionRequired checks if the required fields are not zero-ed
func AssertRegionRequired(obj Region) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"domain": obj.Domain,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegionConstraints checks if the values respects the defined constraints
func AssertRegionConstraints(obj Region) error {
	return nil
}
