// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Kiwi - A Kiwi (Kowabunga Inner Wan Interface) provides edge-network services..
type Kiwi struct {

	// The Kiwi (Kowabunga Inner Wan Interface) provides edge-network services. ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kiwi (Kowabunga Inner Wan Interface) provides edge-network services. name.
	Name string `json:"name"`

	// The Kiwi (Kowabunga Inner Wan Interface) provides edge-network services. description.
	Description string `json:"description,omitempty"`

	// a list of existing remote agents managing the network gateway.
	Agents []string `json:"agents,omitempty"`
}

// AssertKiwiRequired checks if the required fields are not zero-ed
func AssertKiwiRequired(obj Kiwi) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKiwiConstraints checks if the values respects the defined constraints
func AssertKiwiConstraints(obj Kiwi) error {
	return nil
}
