// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// User - A Kowabunga user.
type User struct {

	// The Kowabunga user ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kowabunga user name.
	Name string `json:"name"`

	// The Kowabunga user description.
	Description string `json:"description,omitempty"`

	// User email address.
	Email string `json:"email"`

	// The Kowabunga user role.
	Role string `json:"role"`

	// Whether or not to receive email notifications on events.
	Notifications bool `json:"notifications,omitempty"`
}

// AssertUserRequired checks if the required fields are not zero-ed
func AssertUserRequired(obj User) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"email": obj.Email,
		"role": obj.Role,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserConstraints checks if the values respects the defined constraints
func AssertUserConstraints(obj User) error {
	return nil
}
