// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// UserCredentials - A Kowabunga user login credentials.
type UserCredentials struct {

	// The user email address for login.
	Email string `json:"email"`

	// The user password for login.
	Password string `json:"password"`

	// The resulting server-generated JWT token for Bearer Authentication (read-only).
	Jwt string `json:"jwt,omitempty"`
}

// AssertUserCredentialsRequired checks if the required fields are not zero-ed
func AssertUserCredentialsRequired(obj UserCredentials) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserCredentialsConstraints checks if the values respects the defined constraints
func AssertUserCredentialsConstraints(obj UserCredentials) error {
	return nil
}
