// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KaktusCpu - A Kaktus computing node CPU characteristics.
type KaktusCpu struct {

	// The Kaktus computing node CPU architecture.
	Arch string `json:"arch"`

	// The Kaktus computing node CPU model.
	Model string `json:"model"`

	// The Kaktus computing node CPU vendor.
	Vendor string `json:"vendor"`

	// The Kaktus computing node CPU number of sockets.
	Sockets int64 `json:"sockets"`

	// The Kaktus computing node CPU number of cores.
	Cores int64 `json:"cores"`

	// The Kaktus computing node CPU number of threads.
	Threads int64 `json:"threads"`
}

// AssertKaktusCpuRequired checks if the required fields are not zero-ed
func AssertKaktusCpuRequired(obj KaktusCpu) error {
	elements := map[string]interface{}{
		"arch": obj.Arch,
		"model": obj.Model,
		"vendor": obj.Vendor,
		"sockets": obj.Sockets,
		"cores": obj.Cores,
		"threads": obj.Threads,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKaktusCpuConstraints checks if the values respects the defined constraints
func AssertKaktusCpuConstraints(obj KaktusCpu) error {
	return nil
}
