// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KawaiiFirewall - A Kawaii public firewall settings.
type KawaiiFirewall struct {

	// The Kawaii public firewall list of ingress rules. Kawaii default policy is to drop all incoming traffic, including ICMP. Specified ruleset will be explicitly accepted.
	Ingress []KawaiiFirewallIngressRule `json:"ingress,omitempty"`

	// The default public traffic egress policy.
	EgressPolicy string `json:"egress_policy,omitempty"`

	// The Kawaii public firewall list of egress rules. Kawaii default policy is to accept all outgoing traffic, including ICMP. Specified ruleset will be explicitly dropped if egress_policy is set to accept, and explicitly accepted if egress policy is set to drop..
	Egress []KawaiiFirewallEgressRule `json:"egress,omitempty"`
}

// AssertKawaiiFirewallRequired checks if the required fields are not zero-ed
func AssertKawaiiFirewallRequired(obj KawaiiFirewall) error {
	for _, el := range obj.Ingress {
		if err := AssertKawaiiFirewallIngressRuleRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Egress {
		if err := AssertKawaiiFirewallEgressRuleRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertKawaiiFirewallConstraints checks if the values respects the defined constraints
func AssertKawaiiFirewallConstraints(obj KawaiiFirewall) error {
	for _, el := range obj.Ingress {
		if err := AssertKawaiiFirewallIngressRuleConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Egress {
		if err := AssertKawaiiFirewallEgressRuleConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
