// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// StoragePool - A storage pool.
type StoragePool struct {

	// The storage pool ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The storage pool name.
	Name string `json:"name"`

	// The storage pool description.
	Description string `json:"description,omitempty"`

	// Ceph pool name.
	Pool string `json:"pool"`

	// Ceph Monitor(s) address or FQDN.
	CephAddress string `json:"ceph_address,omitempty"`

	// Ceph Monitor(s) port (default 3300).
	CephPort int64 `json:"ceph_port,omitempty"`

	// The libvirt secret UUID for CephX authentication.
	CephSecretUuid string `json:"ceph_secret_uuid,omitempty"`

	Cost Cost `json:"cost,omitempty"`

	// a list of existing remote agents managing the storage pool.
	Agents []string `json:"agents"`
}

// AssertStoragePoolRequired checks if the required fields are not zero-ed
func AssertStoragePoolRequired(obj StoragePool) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"pool": obj.Pool,
		"agents": obj.Agents,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCostRequired(obj.Cost); err != nil {
		return err
	}
	return nil
}

// AssertStoragePoolConstraints checks if the values respects the defined constraints
func AssertStoragePoolConstraints(obj StoragePool) error {
	if err := AssertCostConstraints(obj.Cost); err != nil {
		return err
	}
	return nil
}
