// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KawaiiVpcNetIpZone - A Kawaii VPC Network IP zone settings.
type KawaiiVpcNetIpZone struct {

	// The Kawaii zone name (read-only).
	Zone string `json:"zone"`

	// The Kawaii zone gateway private IP address in VPC peered subnet  (read-only).
	Private string `json:"private"`
}

// AssertKawaiiVpcNetIpZoneRequired checks if the required fields are not zero-ed
func AssertKawaiiVpcNetIpZoneRequired(obj KawaiiVpcNetIpZone) error {
	elements := map[string]interface{}{
		"zone": obj.Zone,
		"private": obj.Private,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKawaiiVpcNetIpZoneConstraints checks if the values respects the defined constraints
func AssertKawaiiVpcNetIpZoneConstraints(obj KawaiiVpcNetIpZone) error {
	return nil
}
