// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Agent - A Kowabunga remote agent.
type Agent struct {

	// The Kowabunga remote agent ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The Kowabunga remote agent name.
	Name string `json:"name"`

	// The Kowabunga remote agent description.
	Description string `json:"description,omitempty"`

	// The Kowabunga agent type.
	Type string `json:"type"`
}

// AssertAgentRequired checks if the required fields are not zero-ed
func AssertAgentRequired(obj Agent) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"type": obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAgentConstraints checks if the values respects the defined constraints
func AssertAgentConstraints(obj Agent) error {
	return nil
}
