// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KawaiiNetIpZone - A Kawaii Network IP zone settings.
type KawaiiNetIpZone struct {

	// The Kawaii zone name (read-only).
	Zone string `json:"zone"`

	// The Kawaii zone gateway public virtual IP (read-only).
	Public string `json:"public"`

	// The Kawaii zone gateway private virtual IP (read-only).
	Private string `json:"private"`
}

// AssertKawaiiNetIpZoneRequired checks if the required fields are not zero-ed
func AssertKawaiiNetIpZoneRequired(obj KawaiiNetIpZone) error {
	elements := map[string]interface{}{
		"zone": obj.Zone,
		"public": obj.Public,
		"private": obj.Private,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKawaiiNetIpZoneConstraints checks if the values respects the defined constraints
func AssertKawaiiNetIpZoneConstraints(obj KawaiiNetIpZone) error {
	return nil
}
