// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Adapter - A network adapter.
type Adapter struct {

	// The network adapter ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The network adapter name.
	Name string `json:"name"`

	// The network adapter description.
	Description string `json:"description,omitempty"`

	// The network adapter hardware address (e.g. 00:11:22:33:44:55). Auto-generated if unspecified.
	Mac string `json:"mac,omitempty"`

	// The network adapter list of associated IPv4 addresses.
	Addresses []string `json:"addresses,omitempty"`

	// The network adapter is a reserved adapter (e.g. router), where the same hardware address can be reused over several subnets.
	Reserved bool `json:"reserved,omitempty"`
}

// AssertAdapterRequired checks if the required fields are not zero-ed
func AssertAdapterRequired(obj Adapter) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAdapterConstraints checks if the values respects the defined constraints
func AssertAdapterConstraints(obj Adapter) error {
	return nil
}
