// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// ProjectResources - A global project resource quotas/usage (0 for unlimited).
type ProjectResources struct {

	// The maximum total number of vCPUs allowed to be consumed by sum of all instances.
	Vcpus int32 `json:"vcpus,omitempty"`

	// The maximum total memory (in bytes) allowed to be consumed by sum of all instances.
	Memory int64 `json:"memory,omitempty"`

	// The maximum total disk capacity allowed to be consumed by sum of all instances.
	Storage int64 `json:"storage,omitempty"`

	// The maximum number of instances allowed to be spawned.
	Instances int32 `json:"instances,omitempty"`
}

// AssertProjectResourcesRequired checks if the required fields are not zero-ed
func AssertProjectResourcesRequired(obj ProjectResources) error {
	return nil
}

// AssertProjectResourcesConstraints checks if the values respects the defined constraints
func AssertProjectResourcesConstraints(obj ProjectResources) error {
	return nil
}
