// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Instance - A virtual machine instance.
type Instance struct {

	// The virtual machine instance ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The virtual machine instance name.
	Name string `json:"name"`

	// The virtual machine instance description.
	Description string `json:"description,omitempty"`

	// The virtual machine instance memory size (in bytes).
	Memory int64 `json:"memory"`

	// The virtual machine instance number of vCPUs.
	Vcpus int64 `json:"vcpus"`

	// a list of existing network adapters to be connected to the instance.
	Adapters []string `json:"adapters,omitempty"`

	// volumes list of existing storage volumes (i.e. disks) to be connected to the instance.
	Volumes []string `json:"volumes,omitempty"`
}

// AssertInstanceRequired checks if the required fields are not zero-ed
func AssertInstanceRequired(obj Instance) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"memory": obj.Memory,
		"vcpus": obj.Vcpus,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInstanceConstraints checks if the values respects the defined constraints
func AssertInstanceConstraints(obj Instance) error {
	return nil
}
