// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KonveyEndpoint - A Konvey Endpoint Service settings.
type KonveyEndpoint struct {

	// The Konvey (Kowabunga Network Load-Balancer) endpoint name.
	Name string `json:"name"`

	// The port to be exposed.
	Port int64 `json:"port"`

	// The transport layer protocol to be exposed.
	Protocol string `json:"protocol"`

	Backends KonveyBackends `json:"backends"`
}

// AssertKonveyEndpointRequired checks if the required fields are not zero-ed
func AssertKonveyEndpointRequired(obj KonveyEndpoint) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"port": obj.Port,
		"protocol": obj.Protocol,
		"backends": obj.Backends,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertKonveyBackendsRequired(obj.Backends); err != nil {
		return err
	}
	return nil
}

// AssertKonveyEndpointConstraints checks if the values respects the defined constraints
func AssertKonveyEndpointConstraints(obj KonveyEndpoint) error {
	if err := AssertKonveyBackendsConstraints(obj.Backends); err != nil {
		return err
	}
	return nil
}
