// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// InstanceState - A virtual machine instance state.
type InstanceState struct {

	// The virtual machine instance state.
	State string `json:"state"`

	// The virtual machine instance reason of the state.
	Reason string `json:"reason"`
}

// AssertInstanceStateRequired checks if the required fields are not zero-ed
func AssertInstanceStateRequired(obj InstanceState) error {
	elements := map[string]interface{}{
		"state": obj.State,
		"reason": obj.Reason,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInstanceStateConstraints checks if the values respects the defined constraints
func AssertInstanceStateConstraints(obj InstanceState) error {
	return nil
}
