// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Password - A user plain-text password.
type Password struct {

	// The plain-text password.
	Value string `json:"value"`
}

// AssertPasswordRequired checks if the required fields are not zero-ed
func AssertPasswordRequired(obj Password) error {
	elements := map[string]interface{}{
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPasswordConstraints checks if the values respects the defined constraints
func AssertPasswordConstraints(obj Password) error {
	return nil
}
