// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// RegionSubnet - A region/subnet map.
type RegionSubnet struct {

	// The region key.
	Key string `json:"key,omitempty"`

	// The subnet ID.
	Value string `json:"value,omitempty"`
}

// AssertRegionSubnetRequired checks if the required fields are not zero-ed
func AssertRegionSubnetRequired(obj RegionSubnet) error {
	return nil
}

// AssertRegionSubnetConstraints checks if the values respects the defined constraints
func AssertRegionSubnetConstraints(obj RegionSubnet) error {
	return nil
}
