// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Cost - A resource cost.
type Cost struct {

	// The unit price information.
	Price float32 `json:"price"`

	// The associated currency.
	Currency string `json:"currency"`
}

// AssertCostRequired checks if the required fields are not zero-ed
func AssertCostRequired(obj Cost) error {
	elements := map[string]interface{}{
		"price": obj.Price,
		"currency": obj.Currency,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCostConstraints checks if the values respects the defined constraints
func AssertCostConstraints(obj Cost) error {
	return nil
}
