// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// IpRange - A reserved IPv4 addresses pool range, non-addressable by Kowabunga.
type IpRange struct {

	// The range's first IP address.
	First string `json:"first"`

	// The range's last IP address.
	Last string `json:"last"`
}

// AssertIpRangeRequired checks if the required fields are not zero-ed
func AssertIpRangeRequired(obj IpRange) error {
	elements := map[string]interface{}{
		"first": obj.First,
		"last": obj.Last,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertIpRangeConstraints checks if the values respects the defined constraints
func AssertIpRangeConstraints(obj IpRange) error {
	return nil
}
