// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Project - A Kowabunga project corresponds to a single tenant, isolated set of resources.
type Project struct {

	// The project ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The project name.
	Name string `json:"name"`

	// The project description.
	Description string `json:"description,omitempty"`

	// Internal domain name (e.g. myproject.acme.com).
	Domain string `json:"domain,omitempty"`

	// Default root password, set at cloud-init instance bootstrap phase. Will be randomly auto-generated at each instance creation if unspecified.
	RootPassword string `json:"root_password,omitempty"`

	// Default service user name, created at cloud-init instance bootstrap phase. Will use Kowabunga's default configuration one if unspecified.
	BootstrapUser string `json:"bootstrap_user,omitempty"`

	// Default public SSH key, to be associated to bootstrap user. Will use Kowabunga's default configuration one if unspecified.
	BootstrapPubkey string `json:"bootstrap_pubkey,omitempty"`

	// A list of tags to be associated to the project.
	Tags []string `json:"tags,omitempty"`

	// A list of metadata to be associated to the project.
	Metadatas []Metadata `json:"metadatas,omitempty"`

	Quotas ProjectResources `json:"quotas,omitempty"`

	// The assigned project VPC private subnets IDs (read-only).
	PrivateSubnets []RegionSubnet `json:"private_subnets,omitempty"`

	// The list of VRRP IDs used by -as-a-service resources within the project virtual network (read-only). Should your application use VRRP for service redundancy, you should use different IDs to prevent issues..
	ReservedVrrpIds []int32 `json:"reserved_vrrp_ids,omitempty"`

	// A list of user teams allowed to administrate the project (i.e. capable of managing internal resources).
	Teams []string `json:"teams"`

	// A list of Kowabunga regions the project is managing resources from.
	Regions []string `json:"regions"`
}

// AssertProjectRequired checks if the required fields are not zero-ed
func AssertProjectRequired(obj Project) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"teams": obj.Teams,
		"regions": obj.Regions,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Metadatas {
		if err := AssertMetadataRequired(el); err != nil {
			return err
		}
	}
	if err := AssertProjectResourcesRequired(obj.Quotas); err != nil {
		return err
	}
	for _, el := range obj.PrivateSubnets {
		if err := AssertRegionSubnetRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertProjectConstraints checks if the values respects the defined constraints
func AssertProjectConstraints(obj Project) error {
	for _, el := range obj.Metadatas {
		if err := AssertMetadataConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertProjectResourcesConstraints(obj.Quotas); err != nil {
		return err
	}
	for _, el := range obj.PrivateSubnets {
		if err := AssertRegionSubnetConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
