// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// ApiToken - A Kowabunga authentication security token consists of an API key granting access to resources.
type ApiToken struct {

	// The server-to-server authentication security token ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The server-to-server authentication security token name.
	Name string `json:"name"`

	// The server-to-server authentication security token description.
	Description string `json:"description,omitempty"`

	// Does the API token expires at some stage ?.
	Expire bool `json:"expire"`

	// Expiration date of the token (YYYY-MM-DD format).
	ExpirationDate string `json:"expiration_date,omitempty"`
}

// AssertApiTokenRequired checks if the required fields are not zero-ed
func AssertApiTokenRequired(obj ApiToken) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"expire": obj.Expire,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApiTokenConstraints checks if the values respects the defined constraints
func AssertApiTokenConstraints(obj ApiToken) error {
	return nil
}
