// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




type ApiErrorNotFound struct {

	Status int32 `json:"status"`

	Error string `json:"error"`

	Reason string `json:"reason"`
}

// AssertApiErrorNotFoundRequired checks if the required fields are not zero-ed
func AssertApiErrorNotFoundRequired(obj ApiErrorNotFound) error {
	elements := map[string]interface{}{
		"status": obj.Status,
		"error": obj.Error,
		"reason": obj.Reason,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApiErrorNotFoundConstraints checks if the values respects the defined constraints
func AssertApiErrorNotFoundConstraints(obj ApiErrorNotFound) error {
	return nil
}
