// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KawaiiFirewallIngressRule - A Kawaii public firewall ingress rule.
type KawaiiFirewallIngressRule struct {

	// The source IP or CIDR to accept public traffic from.
	Source string `json:"source,omitempty"`

	// The transport layer protocol to accept public traffic from.
	Protocol string `json:"protocol,omitempty"`

	// The port (or list of ports) to accept public traffic from. Ranges are accepted. Format is a-b,c-d (e.g. 443; 22,80,443; 80,443,3000-3005).
	Ports string `json:"ports"`
}

// AssertKawaiiFirewallIngressRuleRequired checks if the required fields are not zero-ed
func AssertKawaiiFirewallIngressRuleRequired(obj KawaiiFirewallIngressRule) error {
	elements := map[string]interface{}{
		"ports": obj.Ports,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertKawaiiFirewallIngressRuleConstraints checks if the values respects the defined constraints
func AssertKawaiiFirewallIngressRuleConstraints(obj KawaiiFirewallIngressRule) error {
	return nil
}
