// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




type ApiErrorForbidden struct {

	Status int32 `json:"status"`

	Error string `json:"error"`

	Reason string `json:"reason"`
}

// AssertApiErrorForbiddenRequired checks if the required fields are not zero-ed
func AssertApiErrorForbiddenRequired(obj ApiErrorForbidden) error {
	elements := map[string]interface{}{
		"status": obj.Status,
		"error": obj.Error,
		"reason": obj.Reason,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApiErrorForbiddenConstraints checks if the values respects the defined constraints
func AssertApiErrorForbiddenConstraints(obj ApiErrorForbidden) error {
	return nil
}
