// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API documentation
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.52.5
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// InstanceRemoteAccess - A virtual machine instance remote access characteristics.
type InstanceRemoteAccess struct {

	// The virtual machine instance remote access URL.
	Url string `json:"url"`
}

// AssertInstanceRemoteAccessRequired checks if the required fields are not zero-ed
func AssertInstanceRemoteAccessRequired(obj InstanceRemoteAccess) error {
	elements := map[string]interface{}{
		"url": obj.Url,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInstanceRemoteAccessConstraints checks if the values respects the defined constraints
func AssertInstanceRemoteAccessConstraints(obj InstanceRemoteAccess) error {
	return nil
}
