// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.2
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// StorageNfs - A NFS storage.
type StorageNfs struct {

	// The NFS storage ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The NFS storage name.
	Name string `json:"name"`

	// The NFS storage description.
	Description string `json:"description,omitempty"`

	// The associated NFS endpoint FQDN.
	Endpoint string `json:"endpoint"`

	// The underlying associated Ceph volume name.
	Fs string `json:"fs,omitempty"`

	// List of NFS Ganesha API server IP addresses.
	Backends []string `json:"backends,omitempty"`

	// NFS Ganesha API server port (default 54934).
	Port int64 `json:"port,omitempty"`
}

// AssertStorageNfsRequired checks if the required fields are not zero-ed
func AssertStorageNfsRequired(obj StorageNfs) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"endpoint": obj.Endpoint,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertStorageNfsConstraints checks if the values respects the defined constraints
func AssertStorageNfsConstraints(obj StorageNfs) error {
	return nil
}
