// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// KaktusCaps - A Kaktus computing node capability.
type KaktusCaps struct {

	Cpu KaktusCpu `json:"cpu"`

	// The Kaktus computing node memory size (bytes).
	Memory int64 `json:"memory"`
}

// AssertKaktusCapsRequired checks if the required fields are not zero-ed
func AssertKaktusCapsRequired(obj KaktusCaps) error {
	elements := map[string]interface{}{
		"cpu": obj.Cpu,
		"memory": obj.Memory,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertKaktusCpuRequired(obj.Cpu); err != nil {
		return err
	}
	return nil
}

// AssertKaktusCapsConstraints checks if the values respects the defined constraints
func AssertKaktusCapsConstraints(obj KaktusCaps) error {
	if err := AssertKaktusCpuConstraints(obj.Cpu); err != nil {
		return err
	}
	return nil
}
