// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Kowabunga API
 *
 * Kvm Orchestrator With A BUNch of Goods Added
 *
 * API version: 0.53.1
 * Contact: maintainers@kowabunga.cloud
 */

package sdk




// Subnet - A network subnet.
type Subnet struct {

	// The network subnet ID (auto-generated).
	Id string `json:"id,omitempty"`

	// The network subnet name.
	Name string `json:"name"`

	// The network subnet description.
	Description string `json:"description,omitempty"`

	// The network subnet CIDR (e.g. 192.168.0.0/24).
	Cidr string `json:"cidr"`

	// The network subnet router/gateway IP address (e.g. 192.168.0.254).
	Gateway string `json:"gateway"`

	// The network subnet DNS server IP address (gateway value if unspecified).
	Dns string `json:"dns,omitempty"`

	// The list of extra routes to be access through designated gateway (format is 10.0.0.0/8).
	ExtraRoutes []string `json:"extra_routes,omitempty"`

	// The network subnet reserved IPv4 ranges (i.e. no IP address can be assigned from there).
	Reserved []IpRange `json:"reserved,omitempty"`

	// The network subnet IPv4 ranges reserved for per-zone local network gateways (range size must be at least equal to region number of zones).
	GwPool []IpRange `json:"gw_pool,omitempty"`

	// Optional application service type.
	Application string `json:"application,omitempty"`
}

// AssertSubnetRequired checks if the required fields are not zero-ed
func AssertSubnetRequired(obj Subnet) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"cidr": obj.Cidr,
		"gateway": obj.Gateway,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Reserved {
		if err := AssertIpRangeRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.GwPool {
		if err := AssertIpRangeRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSubnetConstraints checks if the values respects the defined constraints
func AssertSubnetConstraints(obj Subnet) error {
	for _, el := range obj.Reserved {
		if err := AssertIpRangeConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.GwPool {
		if err := AssertIpRangeConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
