name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Ubuntu 24.04 LTS (Noble) Packages
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Install package dependencies
        run: sudo apt-get install -y debhelper librados-dev librbd-dev gcc
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Build
        run: make all
      - name: Build Debian package
        run: make deb DIST=noble
      - name: Release Debian Package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ../*.deb
