name: Go Vulnerabilities Check
on:
  push:
    branches:
      - master

jobs:
  govulncheck:
    runs-on: ubuntu-latest

    steps:
      - name: Install package dependencies
        run: sudo apt-get install -y debhelper librados-dev librbd-dev gcc
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        run: make mod
      - name: Run GoVulnCheck security scanner
        run: make vuln
